apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: NodePort
  selector:
    app: nginx
    env: prod
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx.conf: |
    server {
      listen 80;
        location /api/ {
          proxy_pass http://express-service:8080/;
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      }

      location / {
          return 200 'Server OK';
          add_header Content-Type text/plain;
      }
    }

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-proxy-deployement
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
      env: prod
  template:
    metadata:
      name: nginx-proxy-pod
      labels:
        app: nginx
        env: prod
    # annotations:
    #   config-checksum: ${CONFIG_CHECKSUM}
    spec:
      volumes:
        - name: config-volume
          configMap:
            name: nginx-config
      containers:
        - name: nginx-proxy-container
          image: nginx:latest
          ports:
            - containerPort: 80
          volumeMounts:
            - name: config-volume
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: nginx.conf
