# apiVersion: V1
# kind: Pod

# metadata:
#   name: volume-pod

# spec:
#   volumes:
#     - name: volume-sample
#       persistentVolumeClaim:
#         claimName: volume-claim
#   containers:
#     - name: volume-container
#       image: nginx:latest
#       volumeMounts:
#         - mountPath: /usr/share/nginx/html
#           name: volume-sample
#       ports:
#         - containerPort: 80
apiVersion: v1

kind: Pod

metadata: 
  name: postgres-app
  labels:
    app: "postgres"
    env: "gavin"
    version: "1.0"

spec:
  volumes:
    - name: postgres-volume
      persistentVolumeClaim:
        claimName: postgres-pvc
  containers:
    - name: gavinc-postgres
      image: postgres:18.1-trixie
      ports:
        - containerPort: 5432
      volumeMounts:
        - mountPath: "/var/lib/postgresql"
          name: postgres-volume
      env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: password