# apiVersion: v1
# kind: PersistentVolumeClaim

# metadata:
#   name: volume-claim

# spec:
#   storageClassName: manual
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 1Gi

apiVersion: v1

kind: PersistentVolumeClaim

metadata: 
  name: postgres-pvc

spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi