apiVersion: v1
kind: Pod
metadata:
  name: pod-nginx
  labels:
    app: nginx
    env: test
    version: "1.0"

spec:
  containers:
    - name: container-nginx
      image: thaore/mynginx:1.0
      ports:
        - containerPort: 80